import { Endpoints, Methods } from "@/api/constants";
import { Provider } from "@/providers/provider";
import { apiCall } from "@/utils/utils-server";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDetails = await apiCall({
    method: Methods.GET,
    url: Endpoints.USER,
  });

  return (
    <html lang="en">
      <Provider userDetails={userDetails.data}>{children}</Provider>
    </html>
  );
}
