import { apiTemplate } from "@/api/api-template-server";
import { Endpoints, Methods } from "@/api/constants";
import { Provider } from "@/providers/provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDetails = await apiTemplate({
    method: Methods.GET,
    url: Endpoints.USER,
  });

  return (
    <html lang="en">
      <Provider userDetails={userDetails.data}>{children}</Provider>
    </html>
  );
}
